export const BASE_URL_GLOBAL = 'https://www.api.kositutor.in'
export const BASE_URL_LOCAL = 'https://www.sms.com'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const REGISTER = 'register'
